
OBJ_NAME = Series.exe
OBJS = Spinner.cpp Series.cpp CircularBuffer.cpp Fourier.cpp Chain.cpp

CC=x86_64-w64-mingw32-g++
INCLUDE_PATHS=-I./SDL_src/SDL2-2.0.9/x86_64-w64-mingw32/include
LIBRARY_PATHS=-L./SDL_src/SDL2-2.0.9/x86_64-w64-mingw32/lib
COMPILER_FLAGS = -w -Wl,-subsystem,windows
LINKER_FLAGS = -lmingw32 -lSDL2main -lSDL2

all: $(OBJS)
	$(CC) $(OBJS) $(INCLUDE_PATHS) $(LIBRARY_PATHS) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(OBJ_NAME)
