/*
 * Spinner.h
 *
 *  Created on: Feb 5, 2019
 *      Author: robert
 */

#ifndef SPINNER_H_
#define SPINNER_H_


class Spinner{
public:
	double rho, theta, freq;
	// Let the constructor be autogenerated
	static Spinner fromCartesian(double x, double y); // create a spinner from Cartesian space
	const Spinner operator+(const Spinner& inp) const;
	const Spinner operator-(const Spinner& inp) const;
	const double getX() const;
	const double getY() const;
};

#endif /* SPINNER_H_ */
