/*
 * Spinner.h
 *
 *  Created on: Feb 5, 2019
 *      Author: robert
 */

#ifndef SPINNER_H_
#define SPINNER_H_


class Spinner{
public:
	double rho, theta, freq;
	// Let the constructor be autogenerated
	static Spinner fromCartesian(double x, double y); // create a spinner from Cartesian space
	Spinner operator+(const Spinner& inp);
	Spinner operator-(const Spinner& inp);
	double getX();
	double getY();
};

#endif /* SPINNER_H_ */
